### ISSUE TITLE
Why don't we have a package.json file? 

### ISSUE THREAD

**Issue by mwaz** [Nischalkhadka/cypress-starter-kit#8]

**Comment by Nischalkhadka** [comment]
@mwaz To simply run the test for now, we don not need **package.json**. Later when we add more dependencies or packages will be adding the package.json. Anways, I will add the **scripts** to the package.json file.

**Comment by Nischalkhadka** [comment]
@mwaz I have added the package.json file. Hope this solves the issue now.
